version: "3.8"
services:
  db:
    image: postgres:15
    container_name: job-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jobdb
    ports:
      - "5432:5432"
    volumes:
      - jobdb-data:/var/lib/postgresql/data

volumes:
  jobdb-data:
